### ISSUE TITLE
Can't build client

### ISSUE THREAD

**Issue by Rubenoo** [cSploit/client#1]
Hey man, first of all thank you for everything that you've done for this  @Silur .
I'm kinda a noob but i wanted to build this client. But i can't. I don't know if the project isn't finished or anything but here are my logs.

log:  [http://pastebin.com/4nDxUAZQ](url)

**Comment by Silur** [comment]
I've seen that you are using the bleeding-edge nove8-pre version, would you please retry with ~7.4?
I'll also setup up a kali vagrant quickly to reproduce it

**Comment by Rubenoo** [comment]
@Silur I've used nodejs 7.4 instead of 8 pre version. and this solved the problem. Thanks for your help
