### ISSUE TITLE
Errors :(

### ISSUE THREAD

**Issue by Rubenoo** [cSploit/client#3]
Hey i've runned some tests but i got alot of errors, i don't know if this is my fault but here are the logs anyway.

pastebin:  
http://pastebin.com/b70Tfk6f

PS. I was able to build the client apk and install it on my s5 :) good job mate

**Comment by Silur** [comment]
sorry for that, actually the project status currently just a skeleton there are no working tests whatsoever (because there are no frontend functionality) so don't expect tests to run correctly 😄

**Comment by theoneandonly-vector** [comment]
Im just curious..
when could we expect a working .apk-release?
because.. it was mentioned, to be released on december..

Am 19.01.2017 1:46 nachm. schrieb "Silur" <notifications@github.com>:

**Comment by Rubenoo** [comment]
Yeah I thought so, well thank you for everything 😊

**Comment by cioccarellia** [comment]
@theoneandonly-vector http://www.csploit.org/csploit_2-updates/
All cSploit developers are giving the maximum of Their potential to finish this big project
However, in big projects owners cannot exactly determinate the release date
Also, there are not a lot of developers that are working on graphics, so the project is upgrading core but to finish the application we need some UI Developers
"Planned" is different from "We will release"
